#!/usr/bin/env bash
#SBATCH --job-name=cavity
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=8:00:00
#SBATCH --mem-per-cpu=2048M
#SBATCH --output=logs/cavity_%j.log
set -euo pipefail

# 2D lid-driven cavity (thesis sec:nsphys:cavity) on ETHZ Euler.  Runs one config
# (order-2 semi-Lagrangian Nitsche MPI binary) to steady state.  Configs are
# generated by scripts/setup_lid_cavity.py.
#
# Usage:
#   sbatch --export=ALL,CFG=data/config/LidDrivenCavity2D_singular_Re100/LidDrivenCavity2D_singular_Re100.json \
#       scripts/slurm_lid_cavity_euler.sh
# Optional env: EXE, TMPDIR, plus you can override --nodes/--ntasks/--cpus-per-task.

if [[ -n "${SLURM_SUBMIT_DIR:-}" ]]; then cd "$SLURM_SUBMIT_DIR"; fi
if [[ -n "${MODULES:-}" ]]; then eval "$MODULES"; fi

CFG="${CFG:?set CFG=path/to/config.json}"
EXE="${EXE:-./build/semilagrangian_navierstokes_nitsche_order2_mpi}"
RANKS="${SLURM_NTASKS:-1}"
THREADS="${SLURM_CPUS_PER_TASK:-16}"
export TMPDIR="${TMPDIR:-$PWD/tmp}"
# The CSV logger does not create nested dirs; make the outputfile's subdir.
OUT=$(python3 -c "import json; print(json.load(open('$CFG'))['outputfile'])")
mkdir -p tmp logs "out/data/$(dirname "$OUT")" "out/paraview/$(dirname "$OUT")"

echo "[cavity] CFG=$CFG  ranks=$RANKS threads=$THREADS"
omp_env=(OMP_NUM_THREADS="$THREADS" OMP_PROC_BIND=spread OMP_PLACES=cores)
if command -v srun >/dev/null 2>&1 && [[ -n "${SLURM_JOB_ID:-}" ]]; then
    srun --ntasks="$RANKS" --cpus-per-task="$THREADS" --cpu-bind=cores \
        env "${omp_env[@]}" "$EXE" -c "$CFG"
else
    env "${omp_env[@]}" "$EXE" -c "$CFG"
fi

OUT=$(python3 -c "import json,sys; print(json.load(open('$CFG'))['outputfile'])")
echo "[cavity] done; tail of vars CSV:"
tail -5 "out/data/${OUT}_vars.csv" 2>/dev/null || true
