add_executable(hcurl_singlefieldnavierstokes_nitsche hcurl_singlefieldnavierstokes_nitsche.cpp)
target_link_libraries(hcurl_singlefieldnavierstokes_nitsche PRIVATE boundaryoperatorslib mfem Boost::program_options dualfield_project_options)

add_executable(hdiv_singlefieldnavierstokes_nitsche hdiv_singlefieldnavierstokes_nitsche.cpp)
target_link_libraries(hdiv_singlefieldnavierstokes_nitsche PRIVATE boundaryoperatorslib mfem Boost::program_options dualfield_project_options)

add_executable(dualfieldnavierstokes_nitsche dualfieldnavierstokes_nitsche.cpp)
target_link_libraries(dualfieldnavierstokes_nitsche PRIVATE boundaryoperatorslib mfem Boost::program_options dualfield_project_options)


add_executable(hcurl_dualfieldnavierstokes_nitsche hcurl_dualfieldnavierstokes_nitsche.cpp)
target_link_libraries(hcurl_dualfieldnavierstokes_nitsche PRIVATE boundaryoperatorslib mfem Boost::program_options dualfield_project_options)

add_executable(hdiv_dualfieldnavierstokes_nitsche hdiv_dualfieldnavierstokes_nitsche.cpp)
target_link_libraries(hdiv_dualfieldnavierstokes_nitsche PRIVATE boundaryoperatorslib mfem Boost::program_options dualfield_project_options)

add_executable(stokes_nitsche Stokes.cpp)
target_link_libraries(stokes_nitsche PRIVATE boundaryoperatorslib mfem Boost::program_options dualfield_project_options)

add_executable(semilagrangian_navierstokes_nitsche semilagrangian_navierstokes_nitsche.cpp)
target_link_libraries(semilagrangian_navierstokes_nitsche PRIVATE boundaryoperatorslib mfem OpenMP::OpenMP_CXX Boost::program_options dualfield_project_options)


